import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
        display: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'title-desktop': ['64px', { lineHeight: '78px', letterSpacing: '0.06em', fontWeight: '700' }],
        'h1-desktop': ['36px', { lineHeight: '42px', fontWeight: '700' }],
        'h2-desktop': ['20px', { lineHeight: '23px', letterSpacing: '0.01em', fontWeight: '700' }],
        'h3-desktop': ['15px', { lineHeight: '18px', fontWeight: '700' }],
        'body-desktop': ['16px', { lineHeight: '19px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-desktop': ['18px', { lineHeight: '21px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'button-desktop': ['18px', { lineHeight: '21px', letterSpacing: '-0.25px', fontWeight: '600' }],
        'small-desktop': ['15px', { lineHeight: '18px', letterSpacing: '-0.025em', fontWeight: '400' }],
        'title-mobile': ['60px', { lineHeight: '73px', letterSpacing: '0.04em', fontWeight: '700' }],
        'h1-mobile': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'h2-mobile': ['16px', { lineHeight: '19px', letterSpacing: '0.02em', fontWeight: '700' }],
        'h3-mobile': ['11px', { lineHeight: '13px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-mobile': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-mobile': ['14px', { lineHeight: '16px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'button-mobile': ['18px', { lineHeight: '21px', letterSpacing: '-0.25px', fontWeight: '600' }],
        'small-mobile': ['11px', { lineHeight: '13px', letterSpacing: '-0.025em', fontWeight: '400' }],
      },
      colors: {
        'brand-primary': '#9E18B9',
        'brand-secondary': '#0678AB',
        'accent-orange': '#EA6000',
        'accent-green': '#23A300',
        'accent-blue': '#6F34E5',
        'accent-yellow': '#FBB02D',
        'denotative-success': '#157F1F',
        'denotative-error': '#DC1818',
        'btn-primary-bg': '#0896D9',
        'btn-primary-bg-hover': '#056E9E',
        'btn-primary-bg-focus': '#0889C4',
        'btn-secondary-text': '#0896D9',
        'btn-secondary-text-hover': '#056E9E',
        'btn-secondary-bg': 'rgba(8, 150, 217, 0.15)',
        'btn-secondary-bg-hover': 'rgba(4, 82, 118, 0.1)',
        'btn-tertiary-text': 'rgba(6, 102, 147, 0.9)',
        'btn-tertiary-border-hover': '#066693',
        'btn-disabled-bg': '#656576',
        'btn-disabled-text': '#F7F7F6',
        'btn-disabled-secondary-text': '#656576',
        'text-dark': '#0B0B0A',
        'text-light': '#F7F7F6',
        'neutral-dark': '#20201D',
        'neutral-light': '#E3E3DE',
        'bg-light': '#F7F7F6',
        'bg-dark': '#373737',
      },
    },
  },
  plugins: [],
};
export default config;